--INSERT INTO `lecar_db`.`person` (`person_type`, `id`, `email`, `first_name`, `last_name`, `title`, `phone`) VALUES ('Customer', 1, 'melanie.m@gmail.com', 'Melanie', 'Massey', 'MADAME', '0611223344');
--INSERT INTO `lecar_db`.`person` (`person_type`, `id`, `email`, `first_name`, `last_name`, `title`, `phone`) VALUES ('Customer', 2, 'arthur.d@gmail.com', 'Arthur', 'Dupont', 'MONSIEUR', '0644332211');
--INSERT INTO `lecar_db`.`person` (`person_type`, `id`, `email`, `first_name`, `last_name`, `title`, `phone`) VALUES ('Admin', 3, 'alicia.j@gmail.com', 'Alicia', 'Jonquille', 'MADEMOISELLE', '0600000000');
--INSERT INTO `lecar_db`.`person` (`person_type`, `id`, `email`, `first_name`, `last_name`, `title`, `phone`) VALUES ('Admin', 4, 'romeo.p@gmail.com', 'Romeo', 'Philippot', 'MONSIEUR', '0600000001');
--INSERT INTO `lecar_db`.`person` (`person_type`, `id`, `email`, `first_name`, `last_name`, `title`, `phone`) VALUES ('EventLeader', 8, 'laura.m@gmail.com', 'Laura', 'Michelet', 'MADEMOISELLE', '0600000002');
--INSERT INTO `lecar_db`.`person` (`person_type`, `id`, `email`, `first_name`, `last_name`, `title`, `phone`) VALUES ('EventLeader', 9, 'lorene.l@gmail.com', 'Lorene', 'Lebonnec', 'MADEMOISELLE', '0600000003');
--INSERT INTO `lecar_db`.`person` (`person_type`, `id`, `email`, `first_name`, `last_name`, `title`, `phone`) VALUES ('EventLeader', 10, 'xavier.c@gmail.com', 'Xavier', 'Caroulle', 'MONSIEUR', '0600000004');
--INSERT INTO `lecar_db`.`person` (`person_type`, `id`, `email`, `first_name`, `last_name`, `title`, `phone`) VALUES ('EventLeader', 11, 'celine.m@gmail.com', 'Céline', 'Mangeant', 'MADAME', '0600000005');
--
--INSERT INTO `lecar_db`.`customer` (`address_city`, `address_street_name`, `address_street_number`, `address_street_type`, `address_zip_code`, `birthdate`, `role`, `id`) VALUES ('Toulouse', 'du Soleil', 10, 'rue', '31000', '1984-03-31', 'CUSTOMER', 1);
--INSERT INTO `lecar_db`.`customer` (`address_city`, `address_street_name`, `address_street_number`, `address_street_type`, `address_zip_code`, `birthdate`, `role`, `id`) VALUES ('Blagnac', 'du Paradis', 9, 'avenue', '31720', '2008-07-14', 'CUSTOMER', 2);
--
--INSERT INTO `lecar_db`.`admin` (`role`, `id`) VALUES ('ADMIN', 3);
--INSERT INTO `lecar_db`.`admin` (`role`, `id`) VALUES ('ADMIN', 4);
--
--INSERT INTO `lecar_db`.`event_leader` (`company_name`, `job_title`, `id`) VALUES ('Sodexo', 'Communication Group SVP', 8);
--INSERT INTO `lecar_db`.`event_leader` (`company_name`, `job_title`, `id`) VALUES ('Sodexo', 'Audit Group SVP', 9);
--INSERT INTO `lecar_db`.`event_leader` (`company_name`, `job_title`, `id`) VALUES ('Sodexo', 'CIO Group SVP', 10);
--INSERT INTO `lecar_db`.`event_leader` (`company_name`, `job_title`, `id`) VALUES ('David Jones', 'CEO Senior Executive Assistant', 11);
--
--INSERT INTO `lecar_db`.`attendee` (`id`, `first_name`, `last_name`, `gender`,`birthdate`) VALUES (12, 'Rafael', 'Mousse', 'male', '2012-06-05');
--INSERT INTO `lecar_db`.`attendee` (`id`, `first_name`, `last_name`, `gender`,`birthdate`) VALUES (13, 'Lily', 'Depp', 'female', '2015-03-05');
--INSERT INTO `lecar_db`.`attendee` (`id`, `first_name`, `last_name`, `gender`,`birthdate`) VALUES (14, 'Agathe', 'Lavigne', 'female', '2018-09-05');
--
--INSERT INTO `lecar_db`.`roles` (`id`, `rolename`) VALUES ('1', 'ADMIN'), ('2', 'USER');

INSERT INTO `roles` (`id`, `rolename`) VALUES (1, 'ADMIN'), (2, 'USER');